### ISSUE TITLE
Use MDAL to persist mesh

### ISSUE THREAD

**Issue by PeterPetrik** [vcloarec/ReosProject#1]
Have you thought of using MDAL for persistance of the mesh? https://github.com/lutraconsulting/MDAL/issues/121

I think it would be quite straighforward to implement new MDAL API to be able to persist the mesh in 2dm file or edit the mesh.

**Comment by vcloarec** [comment]
Hi,
Indeed, I have thought of using MDAL to save the mesh. But, actually, I am not sure about the good choice.

The mesh actually created or edited are TIN, a simple type of mesh (data are only elevation) but a essential entry for hydraulic modeling and not results data from the model. TIN must be independent of the mesh that support the 2D model and TIN does not have to coincide with this mesh. 

So, I am not sure that the 2dm format file is the best. The other reason is that format seem to came form Aquaveo. I would prefer a more generic or universal format. 

I have thinking too about a own file format, not text format but binary format, so the size of the file will be smaller. The data to store are quite simple (only vertices and faces).

Other reason, the file have to store other information, as hardlines that serve to construct the TIN.

**Comment by vcloarec** [comment]
I have to explore the UGRID format. I don't know if he can store other information, like hardlines.

**Comment by PeterPetrik** [comment]
I would suggest not to reinvent new format and use one of existing. UGRID is probably best long-term solution.

On the other hand, if MDAL will be used for all Input/Output the format is irrelevant, since it is "problem" of MDAL.

**Comment by vcloarec** [comment]
When I wrote that I am not sure of the good choice, that was about the file format, not about MDAL.
In any case, it is clear that MDAL will serve to this mesher for save and/or export meshes.
But, it needs that MDAL can write files... If you need, don't hesitate to ask for contribution to this new feature, I will do with pleasure if I find time !

**Comment by PeterPetrik** [comment]
contributions are always welcomed

**Comment by vcloarec** [comment]
On reflexion, right now, as far as a very good work is done to read mesh and its data with MDAL, it is more convenient, today, to implement directly in this mesher the code to write/read mesh with UGRID format. I am working on it, and it will be done soon.

I think writing a mesh in file with MDAL needs to add new concepts and classes to handle with creating and editing meshes. MDAL is optimized for reading meshes and particular instance of MDAL::Mesh is constructed by the specific driver for each file format to adapt behavior to the format. 
For writing meshes, we need to have a MDAL::Mesh constructed with its frame and data before saving. But I think the C API is not very convenient to handle with as it is not possible to create a MDAL::Mesh instance externaly : it is necessary to implement a C function to transfert mesh's frame and its data to MDAL, MDAL needs to create a MDAL::Mesh instance (which derived class ?) to forward it to the driver for saving.

Furtherore, as UGRID can handle with hardline, and not MDAL, it is also more convenient to implement directly here the reading of the UGRID format.

However, MDAL is essential for reading mesh to display it with QGIS. But, right now, MDAL is not fully compliant with UGRID convention as specified in the issue #131 of MDAL repo #(https://github.com/lutraconsulting/MDAL/issues/131#issue-461359821). So I purpose the PR #139 to make MDAL more compliant (https://github.com/lutraconsulting/MDAL/pull/139#issue-303155687).
