### ISSUE TITLE
Unable to add Data to a Station in the Rainfall Manager

### ISSUE THREAD

**Issue by dreyerlivio** [vcloarec/ReosProject#153]
I am not able to to add data to a Station in the Rainfall Manager ( IDF, Synthetic Rainfall, Gauged Rainfall) . The pop up window to enter a name and description work, howerever nothing is saved to the station data. 

![image](https://user-images.githubusercontent.com/47892153/232968705-3d6cb3db-658b-4c9e-9b25-3a6596e737b4.png)

**Comment by vcloarec** [comment]
Ouch...
I confirm the issue, a bad regression...
Is it version 2.3.0?

**Comment by dreyerlivio** [comment]
Yes version 2.3.0

**Comment by vcloarec** [comment]
So young... 
This is fixed with #154 .
As I think this issue is quite critical, so I will release a 2.3.1 version with this fix as soon as possible...

**Comment by vcloarec** [comment]
@dreyerlivio 
Fix available in the verrsion 2.3.1 that is available to download.
Thanks a lot to report it!!!
