### ISSUE TITLE
Problem registering raster as DEM

### ISSUE THREAD

**Issue by Aaditya-327** [vcloarec/ReosProject#3]
I was not having any problem regarding importing raster as DEM, in previous versions, but in 2.1.0, I get this error saying "This layer is not recognized as possible DEM" when its just a projected raster of SRTM.
![image](https://user-images.githubusercontent.com/30322868/120634309-d00d5e00-c48a-11eb-9f18-de2280147ee1.png)

However ALOS raster file is being processed easily.
I redownloaded SRTM and projected, its still doesn't work.

My original data was Int16, then I projected it to Float32 then it got registered as DEM in SRTM.

**Comment by vcloarec** [comment]
Hi,
It is not a bug but a feature... But a bad feature...
Indeed, I have added a filter for raster layer to recognize DEM raster layer, supposing raster layers have always `float `type.
Bad idea, not considering SRTM have `int` type...
I have to adapt this filter.

Thanks to report this issue.

**Comment by Aaditya-327** [comment]
Thank you for quick response.

**Comment by vcloarec** [comment]
fix by bf1d23365cf4c4f7491aa6e1becbb87b1391b93c
