### ISSUE TITLE
Regarding Lekan suddenly crashing when removing burn lines at less zoom level

### ISSUE THREAD

**Issue by Aaditya-327** [vcloarec/ReosProject#4]
I realized that when I create a burn vector line and zoom out so that it seems like 5mm segment on screen and when I try using remove burn option to remove it, the program crashes.

This usually happens when I double click on the vector line, but sometimes it happens when I click it just once also.

https://user-images.githubusercontent.com/30322868/120670757-7586f880-c4b0-11eb-8e9b-f381ead36891.mp4
I tried it again, it happened even if I zoomed in and I missed the burn line by a little bit.

**Comment by vcloarec** [comment]
fix by adf81f09d11785a623f925ff251adcb4e42b31b2
