### ISSUE TITLE
Lekan has too many duplicate strings to translate

### ISSUE THREAD

**Issue by Aaditya-327** [vcloarec/ReosProject#5]
![image](https://user-images.githubusercontent.com/30322868/120925077-84f78300-c6f6-11eb-82fc-026edb2d7621.png)

Will you copy strings from one project to other if I have completed translation for a project? because they are all the same.
And I don't know how to copy.

**Comment by Aaditya-327** [comment]
I learned how to do it. nvm

**Comment by vcloarec** [comment]
> Will you copy strings from one project to other if I have completed translation for a project? because they are all the same.
> And I don't know how to copy.

Hi, first thanks for the effort for translation.

Maybe it is not necessary to translate the version 2.0. I think I will make the release of the corrected version 2.1 tomorrow, it will not be necessary anymore to have the 2.0. 
But if it is really necessary I will try to backport the translation from 2.1 to 2.0.
So you can just translate the 2.1 version.

For other ressources, no need to do anything for now, the first is empty, the "lekan-application-development" is the dev version that can change a lot so, don't translate it, I wonder if I will not remove it.

By the way, can you share how you treat the repeated string?

Other point, do you know where I can find a Nepal flag in svg format (free version). It is for displaying the language in the translation credits.

**Comment by Aaditya-327** [comment]
There is a option in transifex, that suggests translation of already translated repeated phrases in bottom right.
And after I was done with 2.1, I just downloaded this 
>xliff_lekan_release-2-1--reos-en-ts_ne.xlf 
file and reuploaded it to older versions.

This wikimedia svg is provided by Gov of Nepal and open source
https://commons.wikimedia.org/wiki/File:Flag_of_Nepal.svg
Please don't make a rectangle of our map 😛 use a svg or png instead for double triangle.
