### ISSUE TITLE
New Rainfall rrf and Runoff file rro not being generated when I click new project

### ISSUE THREAD

**Issue by Aaditya-327** [vcloarec/ReosProject#6]
I am trying to create a new project in new region and it would be great if I could create a separate rainfall and runoff file for that specific project. 

But when I click new project, new rainfall and runoff files are not generated. 
I have to manually go in rainfall manager and do save as new file and clear current rainfall runoff data.

Is this a bug? Because I wanted to make one and its not possible currently.

https://user-images.githubusercontent.com/30322868/121470880-88348c80-c9de-11eb-964e-c5d17aa3a343.mp4

**Comment by vcloarec** [comment]
Hi, have you had a look here?
https://github.com/vcloarec/ReosProject/wiki/Using-Lekan#rainfall-manager
This a way to share the file between project. If you really want to have different rainfall/runoff files, but I don't encourage it, you can go to the rainfall manager or runoff manager and "save as" the file.

**Comment by Aaditya-327** [comment]
Ohh okay sounds reasonable. Was confused if it was a feature or a bug.
