### ISSUE TITLE
Issue with TELEMAC BC

### ISSUE THREAD

**Issue by vcloarec** [vcloarec/ReosProject#96]
Result of TELEMAC at the extremity of a boundary condition, here a prescribed level. Same can be observed for prescribed flow. So is it a TELEMAC issue, or a bad definition of the boundary in Lekan ?

![Image](https://user-images.githubusercontent.com/7416892/216371010-3fd7dd7e-7692-43d3-99c9-eb33b26b07ae.gif)

**Comment by nicogodet** [comment]
Hi, 

Never encounter this kind of bad result.
Could you give more detail ?
Topography, boundary type and prescribed value, OPTION FOR LIQUID BOUNDARIES value, mesh,...
My first guess is a bad definition of the boundary (nothing to be ashamed of, it can be tricky sometimes).

**Comment by vcloarec** [comment]
OK, after more investigation, no answer yet, but more info:
I have built a simple test cases:
- a constant inflow at upstream
- a constant level at downstream 
- a quite simple geometry with a large downstream limit with corner far away from the main flow.
- important information: **equation is Finite Volume**, **there is not issue with Finite Element** 

here the files model for the case 2:
[telemac_case-2.zip](https://github.com/vcloarec/ReosProject/files/10902194/telemac_case-2.zip)


Here dynamic results with right-angled corner:
![telemac_case_1](https://user-images.githubusercontent.com/7416892/223211772-37d8858e-bef3-4496-b932-9360fa4c95c1.gif)

Everything seems ok, but if I change the geometry of the upstream corner:
![telemac_case_2](https://user-images.githubusercontent.com/7416892/223211971-7dccc743-5b2c-4b9c-b611-c8f3e19eaa99.gif)

here a zoom on the corner:
![telemac_case_1-2](https://user-images.githubusercontent.com/7416892/223212515-6370a32e-e75e-41a6-b2e8-35010d6c2758.png)
![telemac_case_2-2](https://user-images.githubusercontent.com/7416892/223212520-5abc192c-a1d7-4cc3-99d2-9101bbd5ef8a.png)



Other changes, but with obtuse angle:
![telemac_case_3](https://user-images.githubusercontent.com/7416892/223212170-b2ceaa0d-953e-4f10-9ed9-d5f3a86d8032.gif)

Zoom on corner:
![telemac_case_2-2](https://user-images.githubusercontent.com/7416892/223212569-3da20ca7-a684-41d4-ba5f-5491222a20f9.png)


So, when there is not a righted-angle corner, there is a bias in the velocity...

**Comment by nicogodet** [comment]
Weird

You should ask on TELEMAC forum 
I don't know on which version you are but same result on v8p4r0.

**Comment by vcloarec** [comment]
reported on TELEMAC forum  here: http://www.opentelemac.org/index.php/kunena/16-telemac-2d/14144-bias-on-open-boundary-condition

**Comment by vcloarec** [comment]
@nicogodet 


> I don't know on which version you are but same result on v8p4r0.

my version is v8p3r1 but it seems to works fine with v8p3r2, .....

**Comment by nicogodet** [comment]
In test case you shared, it is with Finite Element
if I switch to FV and on v8p4r0, I have the same issue as described. I didn't try on v8p3r2

**Comment by cosstas** [comment]
Unfortunately, the BIAS error remains with v8p3r2 when switching to FV.
I only had to add
[quote]
DESIRED COURANT NUMBER : 0.9
VARIABLE TIME-STEP : YES
[/quote]
